language: node_js
sudo: required
node_js:
  - "8"
  - "9"
  - "10"
addons:
  chrome: stable
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
